// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlCpU3vpjDWu7r9NReiOmvAetF5Izt8bM',
    appId: '1:524112159131:web:8c07a82daa7c8fd907413e',
    messagingSenderId: '524112159131',
    projectId: 'dbcrudgameshop0257-340c8',
    authDomain: 'dbcrudgameshop0257-340c8.firebaseapp.com',
    storageBucket: 'dbcrudgameshop0257-340c8.firebasestorage.app',
    measurementId: 'G-3LV7G658VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCyM_0vkdsEtecYW7vNskUicaugvCyA_c',
    appId: '1:524112159131:android:8fc0e7824bcef68407413e',
    messagingSenderId: '524112159131',
    projectId: 'dbcrudgameshop0257-340c8',
    storageBucket: 'dbcrudgameshop0257-340c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5-fiUR8tpQZ8KMAllnUoefTY_hpBJ-MU',
    appId: '1:524112159131:ios:0785c1a164ccdd3f07413e',
    messagingSenderId: '524112159131',
    projectId: 'dbcrudgameshop0257-340c8',
    storageBucket: 'dbcrudgameshop0257-340c8.firebasestorage.app',
    iosBundleId: 'com.example.gameshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5-fiUR8tpQZ8KMAllnUoefTY_hpBJ-MU',
    appId: '1:524112159131:ios:0785c1a164ccdd3f07413e',
    messagingSenderId: '524112159131',
    projectId: 'dbcrudgameshop0257-340c8',
    storageBucket: 'dbcrudgameshop0257-340c8.firebasestorage.app',
    iosBundleId: 'com.example.gameshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlCpU3vpjDWu7r9NReiOmvAetF5Izt8bM',
    appId: '1:524112159131:web:ce1920b00179a60607413e',
    messagingSenderId: '524112159131',
    projectId: 'dbcrudgameshop0257-340c8',
    authDomain: 'dbcrudgameshop0257-340c8.firebaseapp.com',
    storageBucket: 'dbcrudgameshop0257-340c8.firebasestorage.app',
    measurementId: 'G-BFVRPNVEM9',
  );
}
